name: Doctest Check
permissions: read-all

on:
  push:
    branches:
      - main
      - develop
      - "*"
      - trunk-merge/**
  pull_request:
    branches:
      - main
      - develop
      - "*"

jobs:
  doctest:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -r requirements_docs.txt

      - name: pip install CRIPT Python SDK local package
        run: python${{ matrix.python-version }} -m pip install -e .

      - name: Run Doctests
        run: python${{ matrix.python-version }} -m pytest -o python_paths=. --doctest-modules src/cript/
        env:
          PY_IGNORE_IMPORTMISMATCH: 1

